[#182563382] - Change e2e container to not run as root
DNAstack/data-connect-trino pull request #37
Opened 2023-11-16 20:56 UTC by dna-minn

2023-11-16 21:16 UTC, sharvari-kapadia reviewed
@prajjwolmondal would you or someone on the publisher team mind looking at this PR since Minn has refactored the test folders so that they get picked up?

2023-11-16 21:16 UTC, sharvari-kapadia commented on e2e-tests/pom.xml
> +						</dynamicDependency>
@dna-minn Would you mind providing some context on these two `dynamicDependency` blocks being added here?

2023-11-17 14:18 UTC, mbarkley requested changes
@dna-minn requesting changes on this one so we don't forget to apply the fixes to the problems we learned about yesterday before merging this.

2023-11-20 19:34 UTC, mbarkley approved these changes
LGTM.

@prajjwolmondal we had to move all the e2e tests from `src/main/java` to `src/test/java` for this new simplified setup to work. Can you or someone else on the publisher team review to confirm that's okay?

2023-11-20 20:35 UTC, usanthan approved these changes

2023-11-20 21:19 UTC, merged